CREATE TABLE IF NOT EXISTS user_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL UNIQUE,
  name VARCHAR(255),
  phone_number VARCHAR(50),
  hometown VARCHAR(255),
  date_of_birth DATE,
  emergency_contact_1_name VARCHAR(255),
  emergency_contact_1_phone VARCHAR(50),
  emergency_contact_2_name VARCHAR(255),
  emergency_contact_2_phone VARCHAR(50),
  emergency_contact_3_name VARCHAR(255),
  emergency_contact_3_phone VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_profiles_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
